//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CompanyDepartment { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}
